### ISSUE TITLE
Automate CHANGELOG.md Release Header

### ISSUE THREAD

**Issue by reynoldsalec** [lando/prepare-release-action#15]
After discussing https://github.com/lando/lando/issues/3710 in our Plugin Contributor Meeting, @AaronFeledy made the suggestion that we automate the insertion of release headers into the CHANGELOG.md.

If we adopt a standard that unreleased changes should be under a `## Unreleased` section, we could have the `prepare-release-action` automatically replace that header with a header in the correct format:

```
## {{VERSION}} - [{{DATE}}](https://github.com/lando/{{REPO}}/releases/tag/{{VERSION}})
```

**Comment by pirog** [comment]
i think this is a great idea!
